ProjectsRails/Blogger/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  root 'welcome#index'

  resources :articles

end

ProjectsRails/Blogger/app/models/article.rb
class Article < ActiveRecord::Base
	validates :title, 	presence: true,
						length: {minimum: 5}
end

ProjectsRails/Blogger/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

ProjectsRails/Blogger/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	def index
		@article =	Article.all
	end
	def show
		@article = Article.find(params[:id])
	end
	def new
		@article = Article.new	
	end

	def edit
		@article = Article.find(params[:id])	
	end

	def create
		@article = Article.new(article_params)

		if @article.save
			redirect_to @article
		else
			render 'new'
		end
	end

	def udpate
		@article = Article.find(params[:id])

		if @article.update(article_params)
			redirect_to @article
		else
			render 'edit'
		end
	end

	private 
	def article_params
		params.require(:article).permit(:title, :text)
	end
end

ProjectsRails/Blogger/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

ProjectsRails/Blogger/app/helpers/application_helper.rb
module ApplicationHelper
end

ProjectsRails/Blogger/app/helpers/articles_helper.rb
module ArticlesHelper
end

ProjectsRails/Blogger/app/helpers/welcome_helper.rb
module WelcomeHelper
end

ProjectsRails/Blogger/app/views/articles/edit.html.haml
%h1 Editing Article
= form_for :article, url: article_path(@article), method: :patch do |f|
	-if @article.errors.any?
		#error_explanation
			%h2	
				= pluralize(@article.errors.count, "error")
					prohibited this article from being saved:
			%ul
				-@article.errors.full_messages.each do |msg|
					%li= msg
	%p
		=f.label :title
		%br
		=f.text_field :title
	%p
		=f.label :text
		%br
		=f.text_area :text	
	%p
        =f.submit
= link_to 'Back', article_path

ProjectsRails/Blogger/app/views/articles/index.html.erb
<h1>Listing Articles</h1>
<%= link_to 'My blogger', controller: 'articles'%>	
<%= link_to 'New Article', new_article_path %>	
<table>
	<thead>
		<tr>
			<th>Title</th>
			<th>text</th>
		</tr>
	</thead>
	<tbody>
		<% @article.each do |art| %>
		<tr>
			<td><%= art.title %></td>
			<td><%= art.text %></td>
			<td><%= link_to 'Show', article_path(art) %></td>
			<td><%= link_to 'Edit', edit_article_path(art) %></td>
		</tr>
		<% end %>
	</tbody>
</table>

ProjectsRails/Blogger/app/views/articles/new.html.erb
<h1>New Article</h1>

<%= form_for :article, url: articles_path do |f| %>
<% if @article.errors.any? %>
<div id="error_explanation">
	<h2>
		<%= pluralize(@article.errors.count, "error") %>
		prohibited
		this article from being saved:
	</h2>
	<ul>
		<% @article.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<% end %>
	</ul>
</div>
<% end %>
<p>
	<%= f.label :title %>
	<%= f.text_field :title %>
</p>

<p>
	<%= f.label :text %>
	<%= f.text_field :text %>
</p>

<p>
	<%= f.submit %>
</p>

<% end %>
<%= link_to 'Back', articles_path %>

ProjectsRails/Blogger/app/views/articles/show.html.erb
<p>
	<strong>Title:</strong>
	<%= @article.title%>
</p>
<p>
	<strong>Text:</strong>
	<%= @article.text%>
</p>
<%= link_to 'Back', controller: 'articles' %>

ProjectsRails/Blogger/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogger</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

ProjectsRails/Blogger/app/views/welcome/index.html.erb
<h1>Hello xD</h1>